language: python

services:
    - couchdb

python:
    - 2.7
#    - 2.6

branches:
  only:
    - develop

before_install:

install:
    - PYLIBDIR=`pip --version | grep -Po '(?<=from ).*(?=/(dist|site)-packages)'`; curl https://raw.github.com/ers-devs/ers-utils/master/xo_setup/site-packages.tar | tar -P --wildcards --transform "s,^,$PYLIBDIR/," -x "site-packages/avahi/*"
    - pip install -r requirements.txt --use-mirrors
    - python setup.py install
    - cd ers-global; mvn package -Dmaven.test.skip=true -f pom_embedded.xml; cd ..

before_script:
    - curl -X PUT http://127.0.0.1:5984/_config/admins/admin -d '"admin"'

script: python tests/test_ers.py
