language: python

services:
    - couchdb

python:
    - 2.7
#    - 2.6

branches:
  only:
    - develop

before_install:
    - sudo apt-get install -qq avahi-utils

install: 
    - pip install -r requirements.txt --use-mirrors
    - python setup.py install

script: python tests/ers_test.py
